export default {
    "primary": "#f0f0f0",
    "accent": "",
    "white": "#FFFFFF",
    "black": "#000000",
    "header": "#f0f0f0",
    "share": "#71ee93",
    "activeButtonColor": "#f8ff13",
    "inActiveButtonColor": "#eaeaea",
    "bottomTabColor": "#4e454a",
    "activeCardColor": "#5afd87",
    "inactiveCardColor": "#f0f0f0",
    "secondaryButtonColor": "#5CFD86",
    "sideMenuBgColor": "#eeeeee",
    "subHeaderBgColor": "#222",
    "fieldError": "#D96900",
    "backgroundColor": "#efefef",
    "txnError": "#ee3e46",
    "txnSuccess": "#25b73a",
    "footerBg": "#333",
    "fontPrimary":"#848484",
    "sideMenuInnerBodyContainer" : "#eee",
    "sideMenulinkStyleBorder" : "#ddd",
    "breadcrumbSubTitle" : '#666',
    "leagueTime" : "#6e6e6e",
    "scrollViewContainerBorder" : "#d7d7d7",
    "pressableContainerBorder" :"#404040",

    "common":{
        "bgColor": '#f0f0f0',
        "bgEventCard": "#fafafa",
        "eventBorderColor": "#ddd",
        "fieldTitle":'#777',
        "txtBorder":'#BFBFBF',
        "txtErrBorder":'#D96900',
        "txtBoxBgColor":'#FFF',
        "errMsg":'#D96900',
        "btnBgColor":'#dfdfdf',
        "btnBorderColor":'#dfdfdf'
    },
    "login":{
        "cntryCodeBgColor":'#DDD'
    },
    "APP_COLOR_WHITE": "#FFF",
    "APP_COLOR_YELLOW": "#f8ff13",
    "APP_COLOR_DARK_BLACK": "#000",
    "APP_COLOR_LITE_BLACK": "#222",
    "APP_COLOR_DIVIDE_SECTION_BLACK": "#333",
    "APP_COLOR_GREY": "#f0f0f0" 
}